version: '3.5'

services:

  angular-latest-example-app:
    container_name: angular-latest-example-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '4200:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
